### ISSUE TITLE
Planned support for the new AzureDevOpsCredentialProvider provider?

### ISSUE THREAD

**Issue by Bandgren** [Parfuemerie-Douglas/scaffolder-backend-module-azure-repositories#16]
Hi!

We are currently running the 1.18.1.next release of backstage, and with the release of 1.18 there has been major work done to the support multiple organizations and by so they have implemented a [AzureDevOpsCredentialProvider](https://github.com/backstage/backstage/pull/18213). Will there be any will to carry this plugin to support the 1.18 backstage version?

Since a beginner at best at typescript a PR from me would probably hurt more then it would help

//Johannes

**Comment by antoniobergas** [comment]
I'm having the same issue. For now I just downgrade to version 1.17.5

https://discord.com/channels/687207715902193673/1154845617756065932

We are discussing here to try to inform all users of the plugin 😁

**Comment by antoniobergas** [comment]
@hevans-dglcom I could maybe make a PR with the needed changes, is that okey with you?

**Comment by sdelbusto** [comment]
@Bandgren any chance to move this PR? same issue here, we are blocked to move forward with new backstage version. :(

**Comment by antoniobergas** [comment]
I opened this RFC to try to find a solution for the situation:

https://github.com/Parfuemerie-Douglas/scaffolder-backend-module-azure-pipelines/issues/30

**Comment by antoniobergas** [comment]
https://github.com/Parfuemerie-Douglas/scaffolder-backend-module-azure-pipelines/issues/30#issuecomment-1762015990
