### ISSUE TITLE
Move to Backstage official repo

### ISSUE THREAD

**Issue by djflocko** [Parfuemerie-Douglas/scaffolder-backend-module-azure-repositories#19]
Why don't you move it to the official Backstage repo?
That might help get more contributions.
We are also looking for this functionality and wonder why it is not part of Backstage itself.

**Comment by antoniobergas** [comment]
Unfortunately Backstage maintainers are thinking on just move all third plugin to external repos:

https://github.com/backstage/backstage/issues/20266

Will give more info on my thoughts on the other plugin: https://github.com/Parfuemerie-Douglas/scaffolder-backend-module-azure-pipelines/issues/30
