### ISSUE TITLE
Feature: Scaffold action for Azure to create a pull request on an existing repository

### ISSUE THREAD

**Issue by fosterm-mw** [Parfuemerie-Douglas/scaffolder-backend-module-azure-repositories#5]
Hi,
I've been using the azure devops git actions in this repository and I was wondering if I could extend the push by adding a checkout to a new branch then developing another action for submitting a PR. I've forked the current repository, are you alright if I create a PR to this scaffolder action?

**Comment by hevans-dglcom** [comment]
Hi @fosterm-mw, no problem!

Once we get the PR merged I will release a new version for you :)

**Comment by brunoscota** [comment]
Hello @hevans-dglcom , Im using your scaffold action. It would be great if you accept the @fosterm-mw PR so I dont need to use 2 diff packeges for the same thing.

**Comment by fosterm-mw** [comment]
I can prepare a PR later today

**Comment by fosterm-mw** [comment]
https://github.com/Parfuemerie-Douglas/scaffolder-backend-module-azure-repositories/pull/6 @hevans-dglcom
