### ISSUE TITLE
Support for Azure DevOps Server

### ISSUE THREAD

**Issue by antoniobergas** [Parfuemerie-Douglas/scaffolder-backend-module-azure-repositories#8]
Hi!

We are trying to use this backstage scaffolder actions, unfortunately, I had and error that make me think that somehow the implementation is not compatible with Azure DevOps Server

![image](https://github.com/Parfuemerie-Douglas/scaffolder-backend-module-azure-repositories/assets/26031467/3db2dd96-1074-47a6-89c7-f974a8d07b74)

Is this possible to implement? Will be awesome to have as the pipelines actions works well with Azure DevOps Server and we want to be able to make PRs with the scaffolder 😊

Thanks!

**Comment by hevans-dglcom** [comment]
Hi, looks like same issue as with the pipelines package, hardcoded "dev.azure.com" hostname.

I can get to it in a couple of days, otherwise you can open a PR same as with the other package.

Thanks

**Comment by certainty3452** [comment]
Hi @antoniobergas,
I pushed the changes in version 0.2.5 of plugin, could you please test and confirm it works for you?

**Comment by antoniobergas** [comment]
Hi! Thanks for take a look on this. Will test it ASAP

**Comment by antoniobergas** [comment]
Hi, I'm sorry for the big delay, still pending to double check, I had no time yet.

We are currently in adoption of Backstage and will need to do more tempaltes in the scaffolder soon, will check then if this works properly.

Sorry and thanks for the hard work

**Comment by antoniobergas** [comment]
Still pending to test this one, will probably have time after the next week

**Comment by antoniobergas** [comment]
Hi @certainty3452 , I would like to ask you about the current state of both backstage plugins!

Do you know something about the rest of maintainers? WE have some topics opened in both that would be great to have some answers! Thanks a lot!


PD: I think your solution its working good for Azure DevOps Server!

**Comment by certainty3452** [comment]
Hi @antoniobergas sorry for being silent last time, had lots of important topics besides of Backstage.
Today I notified  my team and we all will have a look on those opened topics asap. Thanks for your feedback and for being not indifferent ;)

**Comment by antoniobergas** [comment]
@certainty3452 Thanks for the fast response! I'm glad to hear, thanks!

As I mentioned in the [RFC](https://github.com/Parfuemerie-Douglas/scaffolder-backend-module-azure-pipelines/issues/30), let me know if you need some help 😄 I'm willing to make contributions
